language: node_js
# There isn't much gained from testing on old versions of Node. This package is
# meant to run in a browser.
node_js:
  - "node"
env:
  global:
    - secure: "UQqNSiugZvbnNVRQxGFUgSsJ2dnEmoU3H57Wok/aG5iBLrzfWlYoNE7O+vM8JJS0qXI+YxzZHr5HoUr1Cl747BhLbUM56E3fADT4TjLYnN/z9tfVedVhcPaBicEQ8Pw1RXVa1iZ+0bngWUROBwPMBp2Tdmap6NkHo8z9FYmi+y/uxBc+ENsxgR6AFYjnHQ9fBUefiDRtQo8DbZw/ucdQqbDytoCsZydjkXqetTXYERIVk8Um9MwOmRrzcQdDf5wrL8UKmlNaLvVJyJC2ozG+AfuO2SyLpH+cW1Bj+jgDdmNARwh03QVLC3VhLXK9licBYgM7oqGy0/4Aa7FJgIxO8AO1xBP/REWAh2DBRcYOIoMktWGRM2bOBHVc2iwflpA1j7lNsBn1te5OOTNSs89bG0c/vAMyP2mLnsTVwlyNHiSsjYs+rtujvT92NOj2XvgnnedsSxfyUqTy8T3ff4sOy/PSRUsgVeIuN+cOsbQve1d7IqKYvvC0dIKVtI7QdstYUhTkmxaO85ca12xqatMmqnj5/wHK73trjzC6KbdpPcDZiH//zdt20504RSp61hV1LqaQj1dV68FG4j/NJgLco+pOKlEhquNNbOjTXg+EJKgSV3QRotsxfkfRV1eTn00O01aUxm5y+9oW2l5P984blss/yre7uszD0I5aGEMNpLE="
    - secure: "h+QcD/Ruli4nI193anIS8n0WokzrQ1zF448t62SLyGI3XBhEoK5prkk3LnvE59A1B7z6hT3O6iea8CH2dk1rrOqBrVk+K4RvtPFT7POmwcDmZeRkmhI3ThZvm6h2g0RbcLeAPCyoRCVHTYKFGn+YF7UFRtsqJTVb7gAoSgbqqXunZa9WVKrENsAu/kTCSlb6O9ABdz38IMDH4tnOQqvglOiC7QEipUO2QeBLzIovPxtgYUNxWu1kZG8HGn2MPgMytbO+AUJulDBraVUxrpKviuYmrZjr0nrVEi0BQ72IzjdHslks72sYQByQhbtJaO7CvzM+wX1+LA3uTRMvoMBDZB+Yb+O28HFjVRgyYmpVR4N7OYTjO0UKEcLomfoPH2xee2oNy4ah9DcKuQjLYK9SbWnz0PVXepLCz7Uw+Q3thgvjlNBI13ucmZJ20lL/84FWs8xaaHtFv38C0E3tjoEFXWEYwaNzNVdOW+6xYmukDUK9E2vSEGpZZUUOvTLeCQEEk+6Fb5zLm3h7c7aVi1uyTxG+rfr0pCn+qrPSinmAPXLbOJ36f09jR4p0bnaL4hbZKdhtTu6F7Cz8eytNrmHWoPfLtsPTTMVAsZJv8DxqPcg85oE1ngfOI7W5PZAIsV9+LH8T0nHSbm+f6szLW96REO9VvWVrhn2Yk9p+FF7U7OI="
# Developers do not need coveralls installed locally while developing. So
# there's no great benefit to adding it to devDependencies. Instead, we install
# it here.
before_script: npm i --no-save coveralls
script: npm run test -- --browsers=all
after_success: ./node_modules/.bin/coveralls < coverage/lcov.info
